- name: ServiceNow
  hosts: localhost
  sources:
    - name: ServiceNow incident webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: R1 - Incident created
      condition: |
        event.payload.state == "1"
      action:
        debug:
    
    - name: R2 - Incident updated
      condition: |
        event.payload.state != "1"
      action:
        debug:
