- name: Generate vault secret_id
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Recursively find /tmp files older than 2 days
      ansible.builtin.find:
        paths: /etc/receptor
      register: files
      delegate_to: localhost

    - debug: var=files

    - name: Read client-id secret
      ansible.builtin.set_fact:
        client_id_content: "{{ lookup('ansible.builtin.file', '/etc/receptor/secretid_token.json') }}"

    - debug: var=client_id_content
